#!/bin/bash
echo "==================================================================="
echo "                Help/overview  for the MIGRATE shell"
echo "                   (website: popgen.sc.fsu.edu)"
echo "==================================================================="
echo "If the commands do not work send an"
echo "email to Peter Beerli (beerli@fsu.edu) [version 3.6.5, October 2014]"
echo " "
echo " "
cores=`findcores`;
echo "Available commands:"
echo "-------------------"
echo "install_migrate    This installs the MIGRATE package"
echo "install_openmpi    This installs the binary OPENMPI package"
echo "migrate-n          runs migrate-n on a single CPU," 
echo "                   heated chains are multithreaded"
echo "fastmigrate-n      parallel version and will run on $cores processors"
echo "                   when using multiple loci/replicates, needs openmpi" 
echo "migratehelp        this help document"
echo "migrate_kitintro   show the migrate shell splash screen"
echo "status             reports pathes used to find appplications and a"
echo "                   number of system parameters"
echo "findcores          reports number of available cores"
echo "                   [this computer has $cores]"
echo " "





